# https://taskfile.dev

version: '3'

vars:
  PACKAGE: "{{.PWD}}/pytotp_client/"

tasks:
  install-deps:
    sources:
      - pyproject.toml
      - poetry.lock
    cmds:
      - poetry install

  pytest:
    deps:
      - install-deps
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  pytest:auto:
    deps:
      - install-deps
    cmds:
      - poetry run pytest -m "not manual" {{.CLI_ARGS}}

  mypy:
    deps:
      - install-deps
    cmds:
      - poetry run mypy {{.CLI_ARGS}} {{.PACKAGE}}

  bandit:
    deps:
      - install-deps
    cmds:
      - poetry run bandit -r --ini .bandit {{.CLI_ARGS}} {{.PACKAGE}}

  ruff:
    desc: Lint with Ruff
    cmds:
      - poetry run ruff check --fix

  lint:
    desc: run all linters
    cmds:
      - task: ruff
      - task: bandit
      - task: mypy

  test:
    desc: run all tests
    cmds:
      - task: pytest

  test:auto:
    desc: run only auto tests
    cmds:
      - task: pytest:auto

  all:
    desc: run all code formatters, linters, and tests
    cmds:
      - task: lint
      - task: test

